/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro_login;

import alertas.campo_vacio;
import alertas.registro_exitoso;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import clases.cambiar_color;
import clases.conexion;
import clases.metodos_especifico_11NO_TOCAR11;

/**
 *
 * @author l
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    conexion con = new conexion();
    Connection cn = con.conectar();

    campo_vacio cv = new campo_vacio();
    cambiar_color cc = new cambiar_color();
    registro_exitoso re = new registro_exitoso();
    metodos_especifico_11NO_TOCAR11 me = new metodos_especifico_11NO_TOCAR11();

    public Registro() {
        initComponents();
        error_icono.setVisible(false);
        bloquear();
        me.revalidar(user);
        boc();
        area_box.addItem("");
        area_box.addItem("Almacen");
        area_box.addItem("Medica");
        area_box.addItem("Ventanílla"); 
    }
    public static int glob = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        p_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        registro_boton = new javax.swing.JButton();
        ver_disp_boton = new javax.swing.JButton();
        error_icono = new javax.swing.JLabel();
        disponibilidad = new javax.swing.JLabel();
        s_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        area_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Nombre de usuario");

        jLabel2.setText("Elija una contraseña");

        user.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        pass2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel3.setText("confirme la contraseña");

        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Nombre");

        p_apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Primer apellido");

        s_apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Segundo apellido");

        registro_boton.setBackground(new java.awt.Color(153, 153, 153));
        registro_boton.setText("Registrarse");
        registro_boton.setBorder(null);
        registro_boton.setFocusPainted(false);
        registro_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_botonActionPerformed(evt);
            }
        });

        ver_disp_boton.setBackground(new java.awt.Color(153, 153, 153));
        ver_disp_boton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ver_disp_boton.setText("Ver disponibilidad");
        ver_disp_boton.setBorder(null);
        ver_disp_boton.setFocusPainted(false);
        ver_disp_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_disp_botonActionPerformed(evt);
            }
        });

        error_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/error-icon - copia.png"))); // NOI18N

        disponibilidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        s_nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Segundo Nombre");

        jLabel8.setText("Area:");

        area_box.setBackground(new java.awt.Color(204, 204, 204));
        area_box.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(error_icono)
                            .addGap(18, 18, 18)
                            .addComponent(disponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(p_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(s_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(s_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ver_disp_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(registro_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(area_box, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(area_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ver_disp_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_icono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(s_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registro_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bloquear() {
        pass.enable(false);
        pass2.enable(false);
        nombre.enable(false);
        s_nombre.enable(false);
        p_apellido.enable(false);
        s_apellido.enable(false);
        cc.color_rojo_backGround(pass);
        cc.color_rojo_backGround(pass2);
        cc.color_rojo_backGround(nombre);
        cc.color_rojo_backGround(s_nombre);
        cc.color_rojo_backGround(p_apellido);
        cc.color_rojo_backGround(s_apellido);
        glob = 0;
    }

    //borde  negro textfields onClick
    public void boc() {
        cc.clic_border_color(user);
        cc.clic_border_color(pass);
        cc.clic_border_color(pass2);
        cc.clic_border_color(nombre);
        cc.clic_border_color(s_nombre);
        cc.clic_border_color(p_apellido);
        cc.clic_border_color(s_apellido);
    }

    private void ver_disp_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_disp_botonActionPerformed
        cc.color_boton_gris(ver_disp_boton);
        if (user.getText().equals("")) {

        } else {
            try {
                ResultSet rs = null;
                PreparedStatement rrt = cn.prepareStatement("select * from usuarios where usuario = ?");
                rrt.setString(1, user.getText());
                rs = rrt.executeQuery();
                if (rs.next()) {
                    disponibilidad.setText("No disponible");
                    cc.color_label_rojo(disponibilidad);
                    disponibilidad.show();
                    error_icono.show();
                    pass.enable(false);
                    pass2.enable(false);
                    nombre.enable(false);
                    s_nombre.enable(false);
                    p_apellido.enable(false);
                    s_apellido.enable(false);
                    cc.color_rojo_backGround(pass);
                    cc.color_rojo_backGround(pass2);
                    cc.color_rojo_backGround(nombre);
                    cc.color_rojo_backGround(s_nombre);
                    cc.color_rojo_backGround(p_apellido);
                    cc.color_rojo_backGround(s_apellido);
                    glob = 0;
                } else {
                    disponibilidad.show();
                    disponibilidad.setText("Disponible");
                    cc.color_label_verde(disponibilidad);
                    error_icono.hide();
                    pass.enable(true);
                    pass2.enable(true);
                    nombre.enable(true);
                    s_nombre.enable(true);
                    p_apellido.enable(true);
                    s_apellido.enable(true);
                    cc.color_blanco_backGround(pass);
                    cc.color_blanco_backGround(pass2);
                    cc.color_blanco_backGround(nombre);
                    cc.color_blanco_backGround(s_nombre);
                    cc.color_blanco_backGround(p_apellido);
                    cc.color_blanco_backGround(s_apellido);
                    glob = 1;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ver_disp_botonActionPerformed

    private void registro_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_botonActionPerformed

        if (glob == 1) {
            if ((user.getText().equals("")) || (pass.getText().equals("")) || (pass2.getText().equals("")) || (nombre.getText().equals("")) || (p_apellido.getText().equals("")) || (s_apellido.getText().equals("")) || area_box.getSelectedIndex() == 0) {
                cv.setLocationRelativeTo(null);
                cv.setVisible(true);
                cv.setAlwaysOnTop(true);
                if (user.getText().equals("")) {
                    cc.color_rojo_border(user);
                }
                if (pass.getText().equals("")) {
                    cc.color_rojo_border(pass);
                }
                if (pass2.getText().equals("")) {
                    cc.color_rojo_border(pass2);
                }
                if (nombre.getText().equals("")) {
                    cc.color_rojo_border(nombre);
                }
                if (p_apellido.getText().equals("")) {
                    cc.color_rojo_border(p_apellido);
                }
                if (s_apellido.getText().equals("")) {
                    cc.color_rojo_border(s_apellido);
                }
                if (area_box.getSelectedIndex() == 0) {
                    cc.color_rojo_borde(area_box);
                }
            } else {
                if (!pass.getText().equals(pass2.getText())) {
                    campo_vacio cvv = new campo_vacio();
                    cvv.setLocationRelativeTo(null);
                    cvv.setVisible(true);
                    cvv.setAlwaysOnTop(true);
                    cvv.texto.setText("Las contraseñas no coinciden, verifique");
                    cc.color_rojo_border(pass2);

                } else {

                    try {
                        PreparedStatement dd = cn.prepareStatement("insert into usuarios (usuario, contraseña, nombre, s_nombre, p_apellido, s_apellido, acceso, area) values(?,?,?,?,?,?,?,?)");
                        dd.setString(1, user.getText());
                        dd.setString(2, pass.getText());
                        dd.setString(3, nombre.getText());
                        dd.setString(4, s_nombre.getText());
                        dd.setString(5, p_apellido.getText());
                        dd.setString(6, s_apellido.getText());
                        dd.setInt(7, 0);
                        dd.setInt(8, area_box.getSelectedIndex());
                        dd.executeUpdate();
                        re.setLocationRelativeTo(null);
                        re.setVisible(true);
                        re.setAlwaysOnTop(true);
                        this.dispose();
                        cc.color_boton_verde(Login.login);
                        cc.color_boton_gris(Login.registro);
                        me.reset();
                    } catch (SQLException ex) {
                        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        } else {
            if (user.getText().equals("")) {
                cc.color_rojo_border(user);
                cv.setLocationRelativeTo(null);
                cv.setVisible(true);
                cv.setAlwaysOnTop(true);

            } else {
                campo_vacio cvv = new campo_vacio();
                cvv.setLocationRelativeTo(null);
                cvv.texto.setText("Primero verifique si el usuario esta disponible ");
                cvv.setVisible(true);
                cvv.setAlwaysOnTop(true);
                cc.color_boton_rojo(ver_disp_boton);
            }
        }
    }//GEN-LAST:event_registro_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> area_box;
    public static javax.swing.JLabel disponibilidad;
    public static javax.swing.JLabel error_icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField nombre;
    public static javax.swing.JTextField p_apellido;
    public static javax.swing.JPasswordField pass;
    public static javax.swing.JPasswordField pass2;
    public static javax.swing.JButton registro_boton;
    public static javax.swing.JTextField s_apellido;
    public static javax.swing.JTextField s_nombre;
    public static javax.swing.JTextField user;
    public static javax.swing.JButton ver_disp_boton;
    // End of variables declaration//GEN-END:variables
}
